#!/usr/bin/env python3

# Google IT Automation with Python - Interacting with the OS with Python, Log Analysis Using Regular Expressions

# Error statistics script to count the number of error messages generated by the users

import os
import re
import subprocess
import sys
import operator


error_dict = {}
filename = sys.argv[1]

with open(filename, "r") as f:
    lines = f.readlines()
    for line in lines:
        regex = r"(ERROR[\w\s\W]*) "
        result = re.search(regex, line)
        if result is not None:
            # print(result.group().strip())
            error_dict[result.group().strip()] = error_dict.get(result.group().strip(), 0) + 1
f.close()

print(sorted(error_dict.items(), key=operator.itemgetter(1), reverse=True))
